language: c

sudo: false

addons:
  apt:
    packages:
      - libxaw7-dev
      - freeglut3-dev
      - libnetpbm10-dev
      - libgd-dev
      - libplplot-dev
      - libavcodec-dev
      - libblas-dev
      - swig
      - libopenmpi-dev
      - libfftw3-dev
      - libsuitesparse-dev

matrix:
  include:
    - env: PYTHON_VERSION=2.7 RSFROOT=$TRAVIS_BUILD_DIR/RSFROOT
      dist: xenial
    - env: PYTHON_VERSION=3.6 RSFROOT=$TRAVIS_BUILD_DIR/RSFROOT
      dist: xenial

# Install madagascar
install:
  - ./configure
  - make install

# Test
script: 
  - source env.sh 
  - cd book 
  - scons test
