language: c

sudo: false

addons:
  apt:
    packages:
      - libxaw7-dev
      - freeglut3-dev
      - libnetpbm10-dev
      - libgd-dev
      - libplplot-dev
      - libavcodec-dev
      - libblas-dev
      - swig
      - python-numpy
      - libopenmpi-dev
      - libfftw3-dev
      - libsuitesparse-dev

matrix:
  include:
    - env: PYTHON_VERSION=2.7 RSFROOT=$HOME/RSFROOT RSFFIGS=$HOME/RSFROOT/figs
      dist: xenial
    - env: PYTHON_VERSION=3.6 RSFROOT=$HOME/RSFROOT RSFFIGS=$HOME/RSFROOT/figs
      dist: xenial

# Install madagascar
install:
  - ./configure
  - make install

before_script:
  - git clone https://github.com/ahay/figs.git $RSFFIGS

# Test
script: 
  - source env.sh 
  - cd book 
  - scons test
