## Customize the test machine
version: 2
jobs:
  build:
    working_directory: ~/ahay/src
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      RSFROOT: ${HOME}/RSFROOT
      RSFFIGS: ${HOME}/RSFROOT/figs
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    #### Checkout
    - run: git clone https://github.com/ahay/figs.git $RSFFIGS    
    #### Compile
    - run: ./configure && make install && source env.sh
    #### Test
    - run: source env.sh && cd book && scons test
    # Save test results
    - store_test_results:
        path: /tmp/circleci-test-results
    # Save artifacts
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results




    