## Customize the test machine
version: 2
workflows:
  version: 2
  test:
    jobs:
      - python36
      - python27
jobs:
  python36: &test-template
    docker:
    - image: circleci/python:3.6.4
    working_directory: ~/ahay/src
    #parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    #### Install LAPACK BlAS
    - run: 
        command: |
          sudo apt-get install python-pip
          sudo pip install numpy scipy
          sudo apt-get install libblas-dev liblapack-dev
    - run:
        command: |
          echo 'export RSFROOT="$HOME/RSFROOT"'      >> $BASH_ENV
          echo 'export RSFFIGS="$HOME/RSFROOT/figs"' >> $BASH_ENV
    #### Checkout
    - run: git clone https://github.com/ahay/figs.git $RSFFIGS    
    #### Compile
    - run: ./configure && make install && source env.sh
    #### Test
    - run: source env.sh && cd book && scons test
    # Save test results
    - store_test_results:
        path: /tmp/circleci-test-results
    # Save artifacts
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results

  python27:
    <<: *test-template
    docker:
    - image: circleci/python:2.7
