codecov:
  require_ci_to_pass: yes
  max_report_age: off

coverage:
  status:
    project:
      default:
        threshold: 0%
        branches:
          - unittest
fixes:
  - "/home/circleci/RSFROOT/lib/python3.8/site-packages/::/ahay/src/framework/"
